# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for ios

  use_frameworks!
  pod 'Alamofire'
  pod 'PromiseKit'
  pod 'PromiseKit/Alamofire'
  pod 'AwaitKit'
  pod 'SwiftSignalRClient'
  pod 'NMessenger', :git => 'https://github.com/mbalex99/NMessenger', :branch => 'swift4'

  target 'iosTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
